name: Webpacker
version: 1.6.0
description: 'The power of Webpack inside Statamic.'
url: 'https://github.com/jimblue/statamic-addon-webpacker-hub'
developer: jimblue
developer_url: 'https://github.com/jimblue'
commercial: true
